/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AllClientsResponse {
  'clientAccounts' : Array<ClientAccount>,
  'state' : string,
  'invoices' : Array<Invoice>,
  'shipments' : Array<Shipment>,
}
export interface ClientAccount {
  'password' : string,
  'createdAt' : Time,
  'role' : ClientRole,
  'email' : [] | [string],
  'isFirstLogin' : boolean,
  'activeSessionToken' : [] | [string],
  'mobile' : [] | [string],
  'identifier' : string,
  'linkedPrincipal' : [] | [Principal],
  'profile' : UserProfile,
}
export type ClientRole = { 'client' : null } |
  { 'admin' : null };
export interface Coordinates { 'latitude' : number, 'longitude' : number }
export interface Invoice {
  'status' : InvoiceStatus,
  'client' : Principal,
  'dueDate' : Time,
  'invoiceNo' : bigint,
  'amount' : bigint,
}
export type InvoiceStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'overdue' : null };
export interface Shipment {
  'status' : string,
  'client' : Principal,
  'trackingID' : string,
  'location' : string,
  'coordinates' : [] | [Coordinates],
}
export type Time = bigint;
export interface UserProfile {
  'gstNumber' : string,
  'address' : string,
  'companyName' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminLogin' : ActorMethod<[string], [] | [string]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClientAccount' : ActorMethod<
    [
      string,
      string,
      Principal,
      [] | [string],
      [] | [string],
      string,
      string,
      string,
    ],
    [] | [string]
  >,
  'getAllClients' : ActorMethod<[string], [] | [AllClientsResponse]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientInvoicesBySessionToken' : ActorMethod<
    [string],
    { 'noSessionToken' : null } |
      { 'notLinked' : string } |
      { 'success' : Array<Invoice> }
  >,
  'getClientShipmentsBySessionToken' : ActorMethod<
    [string],
    { 'noSessionToken' : null } |
      { 'notLinked' : string } |
      { 'success' : Array<Shipment> }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'provisionClientAccount' : ActorMethod<
    [string, string, Principal],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'validateAdminSession' : ActorMethod<[string], [] | [string]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];