/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClientAccount {
  'clientCode' : string,
  'password' : string,
  'createdAt' : Time,
  'role' : ClientRole,
  'email' : [] | [string],
  'isFirstLogin' : boolean,
  'activeSessionToken' : [] | [string],
  'isLocked' : boolean,
  'mobile' : [] | [string],
  'failedAttempts' : bigint,
  'identifier' : string,
  'profile' : UserProfile,
}
export type ClientRole = { 'client' : null } |
  { 'admin' : null };
export interface LoginHistoryEntry {
  'loginTime' : Time,
  'clientId' : string,
  'identifier' : string,
  'ipAddress' : [] | [string],
}
export type Time = bigint;
export interface UserProfile {
  'gstNumber' : string,
  'address' : string,
  'companyName' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminLogin' : ActorMethod<[string, string], string>,
  'adminLogout' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticateClient' : ActorMethod<
    [string, string, [] | [string]],
    [] | [string]
  >,
  'changeAdminPassword' : ActorMethod<[string, string, string], undefined>,
  'clientSignup' : ActorMethod<[string, string, UserProfile], string>,
  'deleteClientAccount' : ActorMethod<[string, string], boolean>,
  'getAllClientAccounts' : ActorMethod<[string], Array<ClientAccount>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientAccountByCode' : ActorMethod<
    [string, string],
    [] | [ClientAccount]
  >,
  'getLoginHistory' : ActorMethod<[string], Array<LoginHistoryEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'healthCheck' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isMsg91ApiKeyStored' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[{}], {}>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];