/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ClientRole = IDL.Variant({
  'client' : IDL.Null,
  'admin' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'gstNumber' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'mobile' : IDL.Text,
});
export const ClientAccount = IDL.Record({
  'password' : IDL.Text,
  'createdAt' : Time,
  'role' : ClientRole,
  'email' : IDL.Opt(IDL.Text),
  'isFirstLogin' : IDL.Bool,
  'activeSessionToken' : IDL.Opt(IDL.Text),
  'mobile' : IDL.Opt(IDL.Text),
  'identifier' : IDL.Text,
  'linkedPrincipal' : IDL.Opt(IDL.Principal),
  'profile' : UserProfile,
});
export const InvoiceStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'overdue' : IDL.Null,
});
export const Invoice = IDL.Record({
  'status' : InvoiceStatus,
  'client' : IDL.Principal,
  'dueDate' : Time,
  'invoiceNo' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const Coordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const Shipment = IDL.Record({
  'status' : IDL.Text,
  'client' : IDL.Principal,
  'trackingID' : IDL.Text,
  'location' : IDL.Text,
  'coordinates' : IDL.Opt(Coordinates),
});
export const AllClientsResponse = IDL.Record({
  'clientAccounts' : IDL.Vec(ClientAccount),
  'state' : IDL.Text,
  'invoices' : IDL.Vec(Invoice),
  'shipments' : IDL.Vec(Shipment),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClientAccount' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Principal,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Opt(IDL.Text)],
      [],
    ),
  'getAllClients' : IDL.Func([IDL.Text], [IDL.Opt(AllClientsResponse)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientInvoicesBySessionToken' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'noSessionToken' : IDL.Null,
          'notLinked' : IDL.Text,
          'success' : IDL.Vec(Invoice),
        }),
      ],
      ['query'],
    ),
  'getClientShipmentsBySessionToken' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'noSessionToken' : IDL.Null,
          'notLinked' : IDL.Text,
          'success' : IDL.Vec(Shipment),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'provisionClientAccount' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Principal],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'validateAdminSession' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ClientRole = IDL.Variant({ 'client' : IDL.Null, 'admin' : IDL.Null });
  const UserProfile = IDL.Record({
    'gstNumber' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const ClientAccount = IDL.Record({
    'password' : IDL.Text,
    'createdAt' : Time,
    'role' : ClientRole,
    'email' : IDL.Opt(IDL.Text),
    'isFirstLogin' : IDL.Bool,
    'activeSessionToken' : IDL.Opt(IDL.Text),
    'mobile' : IDL.Opt(IDL.Text),
    'identifier' : IDL.Text,
    'linkedPrincipal' : IDL.Opt(IDL.Principal),
    'profile' : UserProfile,
  });
  const InvoiceStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'overdue' : IDL.Null,
  });
  const Invoice = IDL.Record({
    'status' : InvoiceStatus,
    'client' : IDL.Principal,
    'dueDate' : Time,
    'invoiceNo' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const Coordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const Shipment = IDL.Record({
    'status' : IDL.Text,
    'client' : IDL.Principal,
    'trackingID' : IDL.Text,
    'location' : IDL.Text,
    'coordinates' : IDL.Opt(Coordinates),
  });
  const AllClientsResponse = IDL.Record({
    'clientAccounts' : IDL.Vec(ClientAccount),
    'state' : IDL.Text,
    'invoices' : IDL.Vec(Invoice),
    'shipments' : IDL.Vec(Shipment),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClientAccount' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Principal,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Opt(IDL.Text)],
        [],
      ),
    'getAllClients' : IDL.Func([IDL.Text], [IDL.Opt(AllClientsResponse)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientInvoicesBySessionToken' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'noSessionToken' : IDL.Null,
            'notLinked' : IDL.Text,
            'success' : IDL.Vec(Invoice),
          }),
        ],
        ['query'],
      ),
    'getClientShipmentsBySessionToken' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'noSessionToken' : IDL.Null,
            'notLinked' : IDL.Text,
            'success' : IDL.Vec(Shipment),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'provisionClientAccount' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'validateAdminSession' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };