/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'gstNumber' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'mobile' : IDL.Text,
});
export const Time = IDL.Int;
export const ClientRole = IDL.Variant({
  'client' : IDL.Null,
  'admin' : IDL.Null,
});
export const ClientAccount = IDL.Record({
  'clientCode' : IDL.Text,
  'password' : IDL.Text,
  'createdAt' : Time,
  'role' : ClientRole,
  'email' : IDL.Opt(IDL.Text),
  'isFirstLogin' : IDL.Bool,
  'activeSessionToken' : IDL.Opt(IDL.Text),
  'isLocked' : IDL.Bool,
  'mobile' : IDL.Opt(IDL.Text),
  'failedAttempts' : IDL.Nat,
  'identifier' : IDL.Text,
  'profile' : UserProfile,
});
export const LoginHistoryEntry = IDL.Record({
  'loginTime' : Time,
  'clientId' : IDL.Text,
  'identifier' : IDL.Text,
  'ipAddress' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'adminLogout' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticateClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Opt(IDL.Text)],
      [],
    ),
  'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'clientSignup' : IDL.Func([IDL.Text, IDL.Text, UserProfile], [IDL.Text], []),
  'deleteClientAccount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getAllClientAccounts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ClientAccount)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientAccountByCode' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(ClientAccount)],
      ['query'],
    ),
  'getLoginHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LoginHistoryEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'healthCheck' : IDL.Func([], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isMsg91ApiKeyStored' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func([IDL.Record({})], [IDL.Record({})], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'gstNumber' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const Time = IDL.Int;
  const ClientRole = IDL.Variant({ 'client' : IDL.Null, 'admin' : IDL.Null });
  const ClientAccount = IDL.Record({
    'clientCode' : IDL.Text,
    'password' : IDL.Text,
    'createdAt' : Time,
    'role' : ClientRole,
    'email' : IDL.Opt(IDL.Text),
    'isFirstLogin' : IDL.Bool,
    'activeSessionToken' : IDL.Opt(IDL.Text),
    'isLocked' : IDL.Bool,
    'mobile' : IDL.Opt(IDL.Text),
    'failedAttempts' : IDL.Nat,
    'identifier' : IDL.Text,
    'profile' : UserProfile,
  });
  const LoginHistoryEntry = IDL.Record({
    'loginTime' : Time,
    'clientId' : IDL.Text,
    'identifier' : IDL.Text,
    'ipAddress' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'adminLogout' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticateClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Opt(IDL.Text)],
        [],
      ),
    'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'clientSignup' : IDL.Func(
        [IDL.Text, IDL.Text, UserProfile],
        [IDL.Text],
        [],
      ),
    'deleteClientAccount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getAllClientAccounts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ClientAccount)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientAccountByCode' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(ClientAccount)],
        ['query'],
      ),
    'getLoginHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LoginHistoryEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'healthCheck' : IDL.Func([], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isMsg91ApiKeyStored' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func([IDL.Record({})], [IDL.Record({})], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };