/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AllClientsResponse {
    clientAccounts: Array<ClientAccount>;
    state: string;
    invoices: Array<Invoice>;
    shipments: Array<Shipment>;
}
export type Time = bigint;
export interface LoginHistoryEntry {
    loginTime: Time;
    clientId: string;
    identifier: string;
    ipAddress?: string;
}
export interface Shipment {
    status: string;
    client: Principal;
    trackingID: string;
    location: string;
    coordinates?: Coordinates;
}
export interface Coordinates {
    latitude: number;
    longitude: number;
}
export interface ClientAccount {
    password: string;
    createdAt: Time;
    role: ClientRole;
    email?: string;
    isFirstLogin: boolean;
    activeSessionToken?: string;
    mobile?: string;
    identifier: string;
    linkedPrincipal?: Principal;
    profile: UserProfile;
}
export interface Invoice {
    status: InvoiceStatus;
    client: Principal;
    dueDate: Time;
    invoiceNo: bigint;
    amount: bigint;
}
export interface UserProfile {
    gstNumber: string;
    address: string;
    companyName: string;
    mobile: string;
}
export enum ClientRole {
    client = "client",
    admin = "admin"
}
export enum InvoiceStatus {
    pending = "pending",
    paid = "paid",
    overdue = "overdue"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_invalidPhone_success_rateLimited {
    invalidPhone = "invalidPhone",
    success = "success",
    rateLimited = "rateLimited"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminLogin(password: string): Promise<{
        __kind__: "serverError";
        serverError: null;
    } | {
        __kind__: "invalidPassword";
        invalidPassword: null;
    } | {
        __kind__: "success";
        success: string;
    }>;
    adminLogout(token: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clientPasswordLogin(identifier: string, password: string): Promise<{
        __kind__: "success";
        success: {
            clientId: string;
            sessionToken: string;
        };
    } | {
        __kind__: "rateLimited";
        rateLimited: null;
    } | {
        __kind__: "invalidCredentials";
        invalidCredentials: null;
    }>;
    clientSignup(email: string | null, mobile: string | null, password: string, companyName: string, gstNumber: string, address: string): Promise<{
        __kind__: "invalidInput";
        invalidInput: string;
    } | {
        __kind__: "mobileExists";
        mobileExists: null;
    } | {
        __kind__: "emailExists";
        emailExists: null;
    } | {
        __kind__: "success";
        success: string;
    }>;
    createClientAccount(sessionToken: string, identifier: string, password: string, email: string | null, mobile: string | null, companyName: string, gstNumber: string, address: string): Promise<string | null>;
    createInvoice(sessionToken: string, invoiceNo: bigint, amount: bigint, status: string, dueDate: Time, client: Principal): Promise<void>;
    createShipment(sessionToken: string, trackingID: string, status: string, location: string, client: Principal, coordinates: Coordinates | null): Promise<void>;
    deleteInvoice(sessionToken: string, invoiceNo: bigint): Promise<void>;
    deleteShipment(sessionToken: string, trackingID: string): Promise<void>;
    getAllClients(sessionToken: string): Promise<AllClientsResponse | null>;
    getAllShipmentsForMap(sessionToken: string): Promise<Array<Shipment>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClientAccountStatus(sessionToken: string): Promise<{
        __kind__: "unauthenticated";
        unauthenticated: null;
    } | {
        __kind__: "authenticated";
        authenticated: {
            clientId: string;
            isFirstLogin: boolean;
            profile: UserProfile;
        };
    }>;
    getClientInvoicesBySessionToken(sessionToken: string): Promise<{
        __kind__: "noSessionToken";
        noSessionToken: null;
    } | {
        __kind__: "notLinked";
        notLinked: string;
    } | {
        __kind__: "success";
        success: Array<Invoice>;
    }>;
    getClientShipmentsBySessionToken(sessionToken: string): Promise<{
        __kind__: "noSessionToken";
        noSessionToken: null;
    } | {
        __kind__: "notLinked";
        notLinked: string;
    } | {
        __kind__: "success";
        success: Array<Shipment>;
    }>;
    getInvoicesByClient(sessionToken: string): Promise<Array<Invoice>>;
    getLoginHistory(sessionToken: string): Promise<Array<LoginHistoryEntry>>;
    getRevenueData(sessionToken: string): Promise<Array<{
        date: string;
        amount: bigint;
    }>>;
    getShipmentsByClient(sessionToken: string): Promise<Array<Shipment>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    provisionClientAccount(sessionToken: string, identifier: string, password: string): Promise<void>;
    repairMissingLinkedPrincipals(sessionToken: string): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendOtp(phoneNumber: string): Promise<Variant_invalidPhone_success_rateLimited>;
    updateInvoice(sessionToken: string, invoiceNo: bigint, amount: bigint, status: string, dueDate: Time): Promise<void>;
    updateShipment(sessionToken: string, trackingID: string, status: string, location: string, coordinates: Coordinates | null): Promise<void>;
    validateAdminSession(sessionToken: string): Promise<boolean>;
    verifyOtp(phoneNumber: string, otp: string): Promise<{
        __kind__: "expired";
        expired: null;
    } | {
        __kind__: "invalidOtp";
        invalidOtp: null;
    } | {
        __kind__: "notFound";
        notFound: null;
    } | {
        __kind__: "success";
        success: {
            clientId: string;
            sessionToken: string;
        };
    }>;
}
import type { AllClientsResponse as _AllClientsResponse, ClientAccount as _ClientAccount, ClientRole as _ClientRole, Coordinates as _Coordinates, Invoice as _Invoice, InvoiceStatus as _InvoiceStatus, LoginHistoryEntry as _LoginHistoryEntry, Shipment as _Shipment, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminLogin(arg0: string): Promise<{
        __kind__: "serverError";
        serverError: null;
    } | {
        __kind__: "invalidPassword";
        invalidPassword: null;
    } | {
        __kind__: "success";
        success: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogout(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clientPasswordLogin(arg0: string, arg1: string): Promise<{
        __kind__: "success";
        success: {
            clientId: string;
            sessionToken: string;
        };
    } | {
        __kind__: "rateLimited";
        rateLimited: null;
    } | {
        __kind__: "invalidCredentials";
        invalidCredentials: null;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.clientPasswordLogin(arg0, arg1);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clientPasswordLogin(arg0, arg1);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async clientSignup(arg0: string | null, arg1: string | null, arg2: string, arg3: string, arg4: string, arg5: string): Promise<{
        __kind__: "invalidInput";
        invalidInput: string;
    } | {
        __kind__: "mobileExists";
        mobileExists: null;
    } | {
        __kind__: "emailExists";
        emailExists: null;
    } | {
        __kind__: "success";
        success: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.clientSignup(to_candid_opt_n5(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clientSignup(to_candid_opt_n5(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async createClientAccount(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: string | null, arg5: string, arg6: string, arg7: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createClientAccount(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClientAccount(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createInvoice(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: Time, arg5: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createShipment(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Principal, arg5: Coordinates | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createShipment(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShipment(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async deleteInvoice(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0, arg1);
            return result;
        }
    }
    async deleteShipment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShipment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShipment(arg0, arg1);
            return result;
        }
    }
    async getAllClients(arg0: string): Promise<AllClientsResponse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllShipmentsForMap(arg0: string): Promise<Array<Shipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShipmentsForMap(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShipmentsForMap(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientAccountStatus(arg0: string): Promise<{
        __kind__: "unauthenticated";
        unauthenticated: null;
    } | {
        __kind__: "authenticated";
        authenticated: {
            clientId: string;
            isFirstLogin: boolean;
            profile: UserProfile;
        };
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientAccountStatus(arg0);
                return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientAccountStatus(arg0);
            return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientInvoicesBySessionToken(arg0: string): Promise<{
        __kind__: "noSessionToken";
        noSessionToken: null;
    } | {
        __kind__: "notLinked";
        notLinked: string;
    } | {
        __kind__: "success";
        success: Array<Invoice>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientInvoicesBySessionToken(arg0);
                return from_candid_variant_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientInvoicesBySessionToken(arg0);
            return from_candid_variant_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientShipmentsBySessionToken(arg0: string): Promise<{
        __kind__: "noSessionToken";
        noSessionToken: null;
    } | {
        __kind__: "notLinked";
        notLinked: string;
    } | {
        __kind__: "success";
        success: Array<Shipment>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientShipmentsBySessionToken(arg0);
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientShipmentsBySessionToken(arg0);
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoicesByClient(arg0: string): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoicesByClient(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoicesByClient(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoginHistory(arg0: string): Promise<Array<LoginHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoginHistory(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoginHistory(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRevenueData(arg0: string): Promise<Array<{
        date: string;
        amount: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueData(arg0);
            return result;
        }
    }
    async getShipmentsByClient(arg0: string): Promise<Array<Shipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShipmentsByClient(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShipmentsByClient(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async provisionClientAccount(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.provisionClientAccount(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.provisionClientAccount(arg0, arg1, arg2);
            return result;
        }
    }
    async repairMissingLinkedPrincipals(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.repairMissingLinkedPrincipals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.repairMissingLinkedPrincipals(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendOtp(arg0: string): Promise<Variant_invalidPhone_success_rateLimited> {
        if (this.processError) {
            try {
                const result = await this.actor.sendOtp(arg0);
                return from_candid_variant_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendOtp(arg0);
            return from_candid_variant_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateInvoice(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateShipment(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Coordinates | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShipment(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShipment(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async validateAdminSession(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateAdminSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateAdminSession(arg0);
            return result;
        }
    }
    async verifyOtp(arg0: string, arg1: string): Promise<{
        __kind__: "expired";
        expired: null;
    } | {
        __kind__: "invalidOtp";
        invalidOtp: null;
    } | {
        __kind__: "notFound";
        notFound: null;
    } | {
        __kind__: "success";
        success: {
            clientId: string;
            sessionToken: string;
        };
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOtp(arg0, arg1);
                return from_candid_variant_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOtp(arg0, arg1);
            return from_candid_variant_n37(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AllClientsResponse_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AllClientsResponse): AllClientsResponse {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ClientAccount_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientAccount): ClientAccount {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ClientRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientRole): ClientRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceStatus): InvoiceStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_LoginHistoryEntry_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginHistoryEntry): LoginHistoryEntry {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Shipment_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Shipment): Shipment {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Coordinates]): Coordinates | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AllClientsResponse]): AllClientsResponse | null {
    return value.length === 0 ? null : from_candid_AllClientsResponse_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clientAccounts: Array<_ClientAccount>;
    state: string;
    invoices: Array<_Invoice>;
    shipments: Array<_Shipment>;
}): {
    clientAccounts: Array<ClientAccount>;
    state: string;
    invoices: Array<Invoice>;
    shipments: Array<Shipment>;
} {
    return {
        clientAccounts: from_candid_vec_n12(_uploadFile, _downloadFile, value.clientAccounts),
        state: value.state,
        invoices: from_candid_vec_n18(_uploadFile, _downloadFile, value.invoices),
        shipments: from_candid_vec_n23(_uploadFile, _downloadFile, value.shipments)
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    password: string;
    createdAt: _Time;
    role: _ClientRole;
    email: [] | [string];
    isFirstLogin: boolean;
    activeSessionToken: [] | [string];
    mobile: [] | [string];
    identifier: string;
    linkedPrincipal: [] | [Principal];
    profile: _UserProfile;
}): {
    password: string;
    createdAt: Time;
    role: ClientRole;
    email?: string;
    isFirstLogin: boolean;
    activeSessionToken?: string;
    mobile?: string;
    identifier: string;
    linkedPrincipal?: Principal;
    profile: UserProfile;
} {
    return {
        password: value.password,
        createdAt: value.createdAt,
        role: from_candid_ClientRole_n15(_uploadFile, _downloadFile, value.role),
        email: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.email)),
        isFirstLogin: value.isFirstLogin,
        activeSessionToken: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.activeSessionToken)),
        mobile: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.mobile)),
        identifier: value.identifier,
        linkedPrincipal: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.linkedPrincipal)),
        profile: value.profile
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _InvoiceStatus;
    client: Principal;
    dueDate: _Time;
    invoiceNo: bigint;
    amount: bigint;
}): {
    status: InvoiceStatus;
    client: Principal;
    dueDate: Time;
    invoiceNo: bigint;
    amount: bigint;
} {
    return {
        status: from_candid_InvoiceStatus_n21(_uploadFile, _downloadFile, value.status),
        client: value.client,
        dueDate: value.dueDate,
        invoiceNo: value.invoiceNo,
        amount: value.amount
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    client: Principal;
    trackingID: string;
    location: string;
    coordinates: [] | [_Coordinates];
}): {
    status: string;
    client: Principal;
    trackingID: string;
    location: string;
    coordinates?: Coordinates;
} {
    return {
        status: value.status,
        client: value.client,
        trackingID: value.trackingID,
        location: value.location,
        coordinates: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.coordinates))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    loginTime: _Time;
    clientId: string;
    identifier: string;
    ipAddress: [] | [string];
}): {
    loginTime: Time;
    clientId: string;
    identifier: string;
    ipAddress?: string;
} {
    return {
        loginTime: value.loginTime,
        clientId: value.clientId,
        identifier: value.identifier,
        ipAddress: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.ipAddress))
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serverError: null;
} | {
    invalidPassword: null;
} | {
    success: string;
}): {
    __kind__: "serverError";
    serverError: null;
} | {
    __kind__: "invalidPassword";
    invalidPassword: null;
} | {
    __kind__: "success";
    success: string;
} {
    return "serverError" in value ? {
        __kind__: "serverError",
        serverError: value.serverError
    } : "invalidPassword" in value ? {
        __kind__: "invalidPassword",
        invalidPassword: value.invalidPassword
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    client: null;
} | {
    admin: null;
}): ClientRole {
    return "client" in value ? ClientRole.client : "admin" in value ? ClientRole.admin : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    overdue: null;
}): InvoiceStatus {
    return "pending" in value ? InvoiceStatus.pending : "paid" in value ? InvoiceStatus.paid : "overdue" in value ? InvoiceStatus.overdue : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unauthenticated: null;
} | {
    authenticated: {
        clientId: string;
        isFirstLogin: boolean;
        profile: _UserProfile;
    };
}): {
    __kind__: "unauthenticated";
    unauthenticated: null;
} | {
    __kind__: "authenticated";
    authenticated: {
        clientId: string;
        isFirstLogin: boolean;
        profile: UserProfile;
    };
} {
    return "unauthenticated" in value ? {
        __kind__: "unauthenticated",
        unauthenticated: value.unauthenticated
    } : "authenticated" in value ? {
        __kind__: "authenticated",
        authenticated: value.authenticated
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    noSessionToken: null;
} | {
    notLinked: string;
} | {
    success: Array<_Invoice>;
}): {
    __kind__: "noSessionToken";
    noSessionToken: null;
} | {
    __kind__: "notLinked";
    notLinked: string;
} | {
    __kind__: "success";
    success: Array<Invoice>;
} {
    return "noSessionToken" in value ? {
        __kind__: "noSessionToken",
        noSessionToken: value.noSessionToken
    } : "notLinked" in value ? {
        __kind__: "notLinked",
        notLinked: value.notLinked
    } : "success" in value ? {
        __kind__: "success",
        success: from_candid_vec_n18(_uploadFile, _downloadFile, value.success)
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    noSessionToken: null;
} | {
    notLinked: string;
} | {
    success: Array<_Shipment>;
}): {
    __kind__: "noSessionToken";
    noSessionToken: null;
} | {
    __kind__: "notLinked";
    notLinked: string;
} | {
    __kind__: "success";
    success: Array<Shipment>;
} {
    return "noSessionToken" in value ? {
        __kind__: "noSessionToken",
        noSessionToken: value.noSessionToken
    } : "notLinked" in value ? {
        __kind__: "notLinked",
        notLinked: value.notLinked
    } : "success" in value ? {
        __kind__: "success",
        success: from_candid_vec_n23(_uploadFile, _downloadFile, value.success)
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invalidPhone: null;
} | {
    success: null;
} | {
    rateLimited: null;
}): Variant_invalidPhone_success_rateLimited {
    return "invalidPhone" in value ? Variant_invalidPhone_success_rateLimited.invalidPhone : "success" in value ? Variant_invalidPhone_success_rateLimited.success : "rateLimited" in value ? Variant_invalidPhone_success_rateLimited.rateLimited : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expired: null;
} | {
    invalidOtp: null;
} | {
    notFound: null;
} | {
    success: {
        clientId: string;
        sessionToken: string;
    };
}): {
    __kind__: "expired";
    expired: null;
} | {
    __kind__: "invalidOtp";
    invalidOtp: null;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "success";
    success: {
        clientId: string;
        sessionToken: string;
    };
} {
    return "expired" in value ? {
        __kind__: "expired",
        expired: value.expired
    } : "invalidOtp" in value ? {
        __kind__: "invalidOtp",
        invalidOtp: value.invalidOtp
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: {
        clientId: string;
        sessionToken: string;
    };
} | {
    rateLimited: null;
} | {
    invalidCredentials: null;
}): {
    __kind__: "success";
    success: {
        clientId: string;
        sessionToken: string;
    };
} | {
    __kind__: "rateLimited";
    rateLimited: null;
} | {
    __kind__: "invalidCredentials";
    invalidCredentials: null;
} {
    return "success" in value ? {
        __kind__: "success",
        success: value.success
    } : "rateLimited" in value ? {
        __kind__: "rateLimited",
        rateLimited: value.rateLimited
    } : "invalidCredentials" in value ? {
        __kind__: "invalidCredentials",
        invalidCredentials: value.invalidCredentials
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invalidInput: string;
} | {
    mobileExists: null;
} | {
    emailExists: null;
} | {
    success: string;
}): {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "mobileExists";
    mobileExists: null;
} | {
    __kind__: "emailExists";
    emailExists: null;
} | {
    __kind__: "success";
    success: string;
} {
    return "invalidInput" in value ? {
        __kind__: "invalidInput",
        invalidInput: value.invalidInput
    } : "mobileExists" in value ? {
        __kind__: "mobileExists",
        mobileExists: value.mobileExists
    } : "emailExists" in value ? {
        __kind__: "emailExists",
        emailExists: value.emailExists
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClientAccount>): Array<ClientAccount> {
    return value.map((x)=>from_candid_ClientAccount_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Shipment>): Array<Shipment> {
    return value.map((x)=>from_candid_Shipment_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LoginHistoryEntry>): Array<LoginHistoryEntry> {
    return value.map((x)=>from_candid_LoginHistoryEntry_n34(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Coordinates | null): [] | [_Coordinates] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
